apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kms

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: ghcr.io/krishnamohankapri/kms-frontend
    newTag: latest