apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kms

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml

images:
  - name: ghcr.io/krishnamohankapri/kms-backend
    newTag: v1.0.4-e388b2ac