apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-config
  namespace: monitoring
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     debug
        Daemon        off
        Parsers_File  parsers.conf

    [INPUT]
        Name              tail
        Path              /var/log/pods/kms_*/*/*.log
        Path_Key          filename
        Parser            none
        Tag               kube.*
        Refresh_Interval  5
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Read_from_Head    false


    [FILTER]
        Name                record_modifier
        Match               kube.*
        Record              namespace kms

    [FILTER]
        Name                rewrite_tag
        Match               kube.*
        Rule                $filename ^/var/log/pods/kms_(?<pod_name>[^_]+)_(?<pod_uid>[^/]+)/(?<container_name>[^/]+)/.+\.log$ kube.kms.$pod_name.$container_name true
        Emitter_Name        re_emitted

    [FILTER]
        Name                kubernetes
        Match               kube.kms.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Merge_Log           On
        Keep_Log            Off
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off
        Labels              On
        Annotations         Off


    [OUTPUT]
        Name        loki
        Match       kube.kms.*
        Host        loki.monitoring.svc
        Port        3100
        URI         /loki/api/v1/push
        Labels      job=fluentbit
        Auto_kubernetes_labels on
        Remove_keys filename

  parsers.conf: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
